name: Pull Request Labeller
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label PR when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label PR when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Required mail server username:
        username: ${{waynerobbo1992@gmail.com}}
        # Required mail server password:
        password: ${{0876340311Wr.}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: waynerobbo1992@gmail.com,L00162024@stduent.lyit.com
        # Required sender full name (address can be skipped):
        from: Luke Skywalker # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        html_body: file://README.html
        # Optional carbon copy recipients:
        cc: kyloren@example.com,leia@example.com
        # Optional blind carbon copy recipients:
        bcc: r2d2@example.com,hansolo@example.com
        # Optional recipient of the email response:
        reply_to: luke@example.com
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
      
