# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build  
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/
  
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with:
          name: webpack artifacts
          path: public/
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Required mail server username:
          username: ${{waynerobbo1992@gmail.com}}
          # Required mail server password:
          password: ${{0876340311Wr.}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: waynerobbo1992@gmail.com,L00162024@stduent.lyit.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://README.html
          # Optional carbon copy recipients:
          cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          reply_to: luke@example.com
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true

 
